### ISSUE TITLE
npm/node?

### ISSUE THREAD

**Issue by gavinengel** [deviantintegral/mysql-parallel#3]
Do you have any desire to rewrite this into a npm module that can be a dependency for other modules?  I for one would use this in one of my modules.

**Comment by deviantintegral** [comment]
Well, I'd like to keep this as bash and xargs or parallel so I can use it on database servers that don't have the node stack installed. But, I'm totally open to making this a raw npm package if that would be useful.

There's also https://github.com/elliotttf/drush-reloadp which was based on this, uses node, but is dependent on Drush (which is a Drupal CLI tool).

**Comment by gavinengel** [comment]
Understood!  Thank you.

**Comment by gavinengel** [comment]
Well, I would be interested in you making a separate npm for this.  I'd like to incorporate it into one of mine, a small project for dumping Drupal databases.

**Comment by deviantintegral** [comment]
@gavinengel done!

https://www.npmjs.com/package/mysql-parallel

**Comment by gavinengel** [comment]
Great!
